### Entropy weighting KMeans

In [1]:
library(wskm)

Loading required package: latticeExtra
Loading required package: RColorBrewer
Loading required package: clv
Loading required package: cluster
Loading required package: class


In [43]:
# Import data for training models
df <- read.csv("~/mandy/imputed_17_columns.csv")
df <- df[!(names(df) %in% c("X", "CEN_bg_pctConstructionIndustry"))]
sum(is.na(df))

[1] 0

In [44]:
names(df)
#     "score_C4", # Auto Score 
#     "EstMarketValue_C1",
#     "finscr_C4", # Credit Score 
#     "CEN_tr_pctOwnOccSecondMort", 
#     "CEN_bg_pctSeasonalHousingUnits", 
#     "CEN_bg_pctHHincomeLT15K", 
#     "CEN_tr_pctHHInvestIncome", 
#     "CEN_tr_pctHHSocialSecurityIncome",  
#     "CEN_bg_pctLiveAloneHH", 
#     "CEN_tr_pctHSGrad", 
#     "iat89_C4", # Highest delinquency on a trade 
#     "imt01_C4", # Number of mortgages 
#     "IssAgeALB", # Issue Age 
#     "HealthScore_C5", # Health Score 
#     "Length.of.Residence_num", 
#     "Target.Narrow.Band.Income_num" 

[1] "score_C4"                         "EstMarketValue_C1"               
 [3] "finscr_C4"                        "CEN_tr_pctOwnOccSecondMort"      
 [5] "CEN_bg_pctSeasonalHousingUnits"   "CEN_bg_pctHHincomeLT15K"         
 [7] "CEN_tr_pctHHInvestIncome"         "CEN_tr_pctHHSocialSecurityIncome"
 [9] "CEN_bg_pctLiveAloneHH"            "CEN_tr_pctHSGrad"                
[11] "iat89_C4"                         "imt01_C4"                        
[13] "IssAgeALB"                        "HealthScore_C5"                  
[15] "Length.of.Residence_num"          "Target.Narrow.Band.Income_num"

In [46]:
# Scaling is needed for entropy weighting KMeans
df_scale <- scale(df)

In [47]:
# Define function to train ewkm model and store clustering result
cluster_df = data.frame()
fit_ewkm <- function(k, lambda, data, maxiteration){
    ewkm_model <- ewkm(data, k, lambda=lambda, maxiter=maxiteration)
    print(paste0("K = ", k))
    print(paste0("iterations: ", ewkm_model$iterations))
    print(paste0("total.iterations: ", ewkm_model$total.iterations))
    print(paste0("restarts: ", ewkm_model$restarts))
    print(table(ewkm_model$cluster))
    weight=round(ewkm_model$weight, 2)
    print(weight[, colSums(abs(weight)) > 0.1])
    return(ewkm_model)
}

In [51]:
#
k = 4
lambda = 1
ewkm_model = fit_ewkm(k=k, lambda=lambda, data=df_scale, maxiteration=100)
df$ewkm_k4_l1 = ewkm_model$cluster

[1] "K = 4"
[1] "iterations: 35"
[1] "total.iterations: 36"
[1] "restarts: 0"

      1       2       3       4 
 454082  724663  185463 3368490 
  EstMarketValue_C1 iat89_C4
1                 1        0
2                 1        0
3                 1        0
4                 0        1


In [52]:
#
k = 4
lambda = 2
ewkm_model = fit_ewkm(k=k, lambda=lambda, data=df_scale, maxiteration=100)
df$ewkm_k4_l2 = ewkm_model$cluster

[1] "K = 4"
[1] "iterations: 24"
[1] "total.iterations: 25"
[1] "restarts: 0"

      1       2       3       4 
3434327  854308  225766  218297 
  CEN_tr_pctOwnOccSecondMort CEN_bg_pctSeasonalHousingUnits HealthScore_C5
1                          0                              1              0
2                          0                              0              1
3                          1                              0              0
4                          0                              1              0


In [53]:
#
k = 4
lambda = 3
ewkm_model = fit_ewkm(k=k, lambda=lambda, data=df_scale, maxiteration=100)
df$ewkm_k4_l3 = ewkm_model$cluster

[1] "K = 4"
[1] "iterations: 14"
[1] "total.iterations: 15"
[1] "restarts: 0"

      1       2       3       4 
 176814  891489 3412202  252193 
  EstMarketValue_C1 CEN_bg_pctHHincomeLT15K iat89_C4
1                 0                       1        0
2                 0                       0        1
3                 0                       0        1
4                 1                       0        0


In [54]:
#
k = 4
lambda = 4
ewkm_model = fit_ewkm(k=k, lambda=lambda, data=df_scale, maxiteration=100)
df$ewkm_k4_l4 = ewkm_model$cluster

[1] "K = 4"
[1] "iterations: 30"
[1] "total.iterations: 31"
[1] "restarts: 0"

      1       2       3       4 
 815278  803366 1812439 1301615 
  EstMarketValue_C1 CEN_bg_pctHHincomeLT15K
1                 1                       0
2                 0                       1
3                 1                       0
4                 0                       1


In [57]:
#
k = 5
lambda = 1
ewkm_model = fit_ewkm(k=k, lambda=lambda, data=df_scale, maxiteration=100)
df$ewkm_k5_l1 = ewkm_model$cluster
#
lambda = 2
ewkm_model = fit_ewkm(k=k, lambda=lambda, data=df_scale, maxiteration=100)
df$ewkm_k5_l2 = ewkm_model$cluster
#
lambda = 3
ewkm_model = fit_ewkm(k=k, lambda=lambda, data=df_scale, maxiteration=100)
df$ewkm_k5_l3 = ewkm_model$cluster
#
lambda = 4
ewkm_model = fit_ewkm(k=k, lambda=lambda, data=df_scale, maxiteration=100)
df$ewkm_k5_l4 = ewkm_model$cluster

[1] "K = 5"
[1] "iterations: 36"
[1] "total.iterations: 37"
[1] "restarts: 0"

      1       2       3       4       5 
 532211 3284278  349932  287699  278578 
  EstMarketValue_C1 CEN_bg_pctSeasonalHousingUnits CEN_bg_pctHHincomeLT15K
1                 1                              0                       0
2                 0                              1                       0
3                 0                              0                       1
4                 1                              0                       0
5                 0                              0                       1
[1] "K = 5"
[1] "iterations: 38"
[1] "total.iterations: 39"
[1] "restarts: 0"

      1       2       3       4       5 
 357488 3409319  269302  446555  250034 
  EstMarketValue_C1 CEN_bg_pctHHincomeLT15K iat89_C4
1                 0                       1        0
2                 0                       0        1
3                 1                       0        0
4               

In [58]:
dim(df)

[1] 4732698      25

In [59]:
#
k = 6
lambda = 1
ewkm_model = fit_ewkm(k=k, lambda=lambda, data=df_scale, maxiteration=100)
df$ewkm_k6_l1 = ewkm_model$cluster
#
lambda = 2
ewkm_model = fit_ewkm(k=k, lambda=lambda, data=df_scale, maxiteration=100)
df$ewkm_k6_l2 = ewkm_model$cluster
#
lambda = 3
ewkm_model = fit_ewkm(k=k, lambda=lambda, data=df_scale, maxiteration=100)
df$ewkm_k6_l3 = ewkm_model$cluster
#
lambda = 4
ewkm_model = fit_ewkm(k=k, lambda=lambda, data=df_scale, maxiteration=100)
df$ewkm_k6_l4 = ewkm_model$cluster

[1] "K = 6"
[1] "iterations: 59"
[1] "total.iterations: 60"
[1] "restarts: 0"

      1       2       3       4       5       6 
 330065   46891   11467   44593 3408819  890863 
  EstMarketValue_C1 CEN_bg_pctSeasonalHousingUnits iat89_C4
1                 0                              1        0
2                 1                              0        0
3                 0                              1        0
4                 0                              1        0
5                 0                              0        1
6                 0                              0        1
[1] "K = 6"
[1] "iterations: 55"
[1] "total.iterations: 56"
[1] "restarts: 0"

      1       2       3       4       5       6 
 303627  131966 1434698 2277006  329804  255597 
  EstMarketValue_C1 CEN_bg_pctSeasonalHousingUnits CEN_bg_pctHHincomeLT15K
1                 1                              0                       0
2                 1                              0                       0
3

In [60]:
dim(df)

[1] 4732698      28

In [61]:
#
k = 7
lambda = 1
ewkm_model = fit_ewkm(k=k, lambda=lambda, data=df_scale, maxiteration=100)
df$ewkm_k7_l1 = ewkm_model$cluster
#
lambda = 2
ewkm_model = fit_ewkm(k=k, lambda=lambda, data=df_scale, maxiteration=100)
df$ewkm_k7_l2 = ewkm_model$cluster
#
lambda = 3
ewkm_model = fit_ewkm(k=k, lambda=lambda, data=df_scale, maxiteration=100)
df$ewkm_k7_l3 = ewkm_model$cluster
#
lambda = 4
ewkm_model = fit_ewkm(k=k, lambda=lambda, data=df_scale, maxiteration=100)
df$ewkm_k7_l4 = ewkm_model$cluster

[1] "K = 7"
[1] "iterations: 39"
[1] "total.iterations: 42"
[1] "restarts: 1"

      1       2       3       4       5       6       7 
1364154   32162  626276   19420 2624673   39958   26055 
  EstMarketValue_C1 CEN_bg_pctSeasonalHousingUnits CEN_bg_pctHHincomeLT15K
1                 0                              1                       0
2                 0                              1                       0
3                 0                              0                       0
4                 0                              0                       0
5                 0                              0                       0
6                 1                              0                       0
7                 0                              0                       1
  CEN_tr_pctHHSocialSecurityIncome iat89_C4
1                                0        0
2                                0        0
3                                0        1
4                              

In [62]:
dim(df)

[1] 4732698      32

In [63]:
#
k = 8
lambda = 1
ewkm_model = fit_ewkm(k=k, lambda=lambda, data=df_scale, maxiteration=100)
df$ewkm_k8_l1 = ewkm_model$cluster
#
lambda = 2
ewkm_model = fit_ewkm(k=k, lambda=lambda, data=df_scale, maxiteration=100)
df$ewkm_k8_l2 = ewkm_model$cluster
#
lambda = 3
ewkm_model = fit_ewkm(k=k, lambda=lambda, data=df_scale, maxiteration=100)
df$ewkm_k8_l3 = ewkm_model$cluster
#
lambda = 4
ewkm_model = fit_ewkm(k=k, lambda=lambda, data=df_scale, maxiteration=100)
df$ewkm_k8_l4 = ewkm_model$cluster

[1] "K = 8"
[1] "iterations: 41"
[1] "total.iterations: 44"
[1] "restarts: 1"

      1       2       3       4       5       6       7       8 
 617345   16669   36374 2574879   22172   27623 1419046   18590 
  EstMarketValue_C1 CEN_tr_pctOwnOccSecondMort CEN_bg_pctSeasonalHousingUnits
1                 0                          0                              0
2                 0                          1                              0
3                 1                          0                              0
4                 0                          0                              0
5                 0                          0                              0
6                 0                          0                              1
7                 0                          0                              1
8                 0                          0                              0
  CEN_bg_pctHHincomeLT15K iat89_C4 imt01_C4
1                       0        1        0
2

In [65]:
#
k = 9
lambda = 1
ewkm_model = fit_ewkm(k=k, lambda=lambda, data=df_scale, maxiteration=100)
df$ewkm_k9_l1 = ewkm_model$cluster
#
lambda = 2
ewkm_model = fit_ewkm(k=k, lambda=lambda, data=df_scale, maxiteration=100)
df$ewkm_k9_l2 = ewkm_model$cluster
#
lambda = 3
ewkm_model = fit_ewkm(k=k, lambda=lambda, data=df_scale, maxiteration=100)
df$ewkm_k9_l3 = ewkm_model$cluster
#
lambda = 4
ewkm_model = fit_ewkm(k=k, lambda=lambda, data=df_scale, maxiteration=100)
df$ewkm_k9_l4 = ewkm_model$cluster

[1] "K = 9"
[1] "iterations: 58"
[1] "total.iterations: 63"
[1] "restarts: 2"

      1       2       3       4       5       6       7       8       9 
 178259 3408921   42164   50743  890739   52560   47762   61547       3 
  score_C4 CEN_tr_pctHHInvestIncome CEN_tr_pctHHSocialSecurityIncome
1     1.00                     0.00                             0.00
2     0.00                     0.00                             0.00
3     0.00                     1.00                             0.00
4     0.00                     1.00                             0.00
5     0.00                     0.00                             0.00
6     0.00                     0.00                             0.00
7     0.00                     0.00                             0.00
8     0.00                     0.00                             1.00
9     0.06                     0.06                             0.06
  CEN_bg_pctLiveAloneHH CEN_tr_pctHSGrad iat89_C4
1                  0.00            

In [66]:
#
k = 10
lambda = 1
ewkm_model = fit_ewkm(k=k, lambda=lambda, data=df_scale, maxiteration=100)
df$ewkm_k10_l1 = ewkm_model$cluster
#
lambda = 2
ewkm_model = fit_ewkm(k=k, lambda=lambda, data=df_scale, maxiteration=100)
df$ewkm_k10_l2 = ewkm_model$cluster
#
lambda = 3
ewkm_model = fit_ewkm(k=k, lambda=lambda, data=df_scale, maxiteration=100)
df$ewkm_k10_l3 = ewkm_model$cluster
#
lambda = 4
ewkm_model = fit_ewkm(k=k, lambda=lambda, data=df_scale, maxiteration=100)
df$ewkm_k10_l4 = ewkm_model$cluster

[1] "K = 10"
[1] "iterations: 81"
[1] "total.iterations: 82"
[1] "restarts: 0"

      1       2       3       4       5       6       7       8       9      10 
  13731   11586  877474  333583   11253   18267   20211   29332   26431 3390830 
   EstMarketValue_C1 CEN_tr_pctOwnOccSecondMort CEN_bg_pctSeasonalHousingUnits
1                  1                          0                              0
2                  0                          1                              0
3                  0                          0                              0
4                  0                          0                              1
5                  0                          0                              0
6                  0                          0                              0
7                  0                          0                              0
8                  1                          0                              0
9                  1                          0

In [67]:
dim(df)

[1] 4732698      44

In [69]:
write.csv(df, file = "ewkm_result.csv")

In [70]:
# score_C4 EstMarketValue_C1 CEN_bg_pctHHincomeLT15K CEN_tr_pctHSGrad
# 1        0                 0                       0                0
# 2        0                 1                       0                0
# 3        1                 0                       0                0
# 4        0                 1                       0                0
# 5        0                 0                       1                0
# 6        0                 1                       0                0
# 7        0                 0                       0                1
#   HealthScore_C5
# 1              1
# 2              0
# 3              0
# 4              0
# 5              0
# 6              0
# 7              0

# 1       2       3       4       5       6       7 
# 2697532  501439  281938  571279  322217  216788  141505 
df_score_c4 <- boxplot(score_C4~ewkm_k7_l3, df, plot = FALSE)$stats
df_EstMarketValue_C1 <- boxplot(EstMarketValue_C1~ewkm_k7_l3, df, plot = FALSE)$stats
df_CEN_bg_pctHHincomeLT15K <- boxplot(CEN_bg_pctHHincomeLT15K~ewkm_k7_l3, df, plot = FALSE)$stats
df_CEN_tr_pctHSGrad <- boxplot(CEN_tr_pctHSGrad~ewkm_k7_l3, df, plot = FALSE)$stats
df_HealthScore_C5 <- boxplot(HealthScore_C5~ewkm_k7_l3, df, plot = FALSE)$stats

In [71]:
df_score_c4

[,1] [,2]    [,3] [,4]     [,5] [,6]     [,7]    
[1,]  21   21.000 681   21.0000  21   21.0000  21.0000
[2,]  83   81.000 747   70.0000  87   93.0000  93.0000
[3,] 161  150.000 769   96.0000 182  195.0000 191.0000
[4,] 745  595.075 791  552.6569 619  601.0809 608.1353
[5,] 899  899.000 857  899.0000 899  899.0000 899.0000

In [72]:
df_EstMarketValue_C1

[,1]   [,2]     [,3]     [,4]      [,5]     [,6]     [,7]     
[1,]      0 161823.2      0.0  22513.19      0.0 287641.2       0.0
[2,] 149000 188000.0 145000.0  90000.00 171000.0 326957.3  268680.8
[3,] 233000 211000.0 246000.0 113842.90 289851.4 356000.0  422000.0
[4,] 385106 235000.0 418000.0 135000.00 493000.0 386000.0  570000.0
[5,] 739265 287641.2 827415.1 161828.37 976000.0 474557.8 1021000.0

In [73]:
df_CEN_bg_pctHHincomeLT15K

[,1]       [,2]       [,3]       [,4]       [,5]       [,6]      
[1,] 0.00000000 0.00000000 0.00000000 0.00000000 0.00400000 0.00000000
[2,] 0.02783300 0.04609475 0.02880658 0.06265356 0.02490170 0.01948052
[3,] 0.06355932 0.08247423 0.07474227 0.10526316 0.03202847 0.07023604
[4,] 0.11718750 0.12998860 0.12888889 0.16568047 0.03888889 0.11727273
[5,] 0.25121556 0.25581395 0.27898551 0.32020202 0.05985915 0.26395939
     [,7]      
[1,] 0.00000000
[2,] 0.01450512
[3,] 0.05955056
[4,] 0.10335196
[5,] 0.23658537

In [74]:
df_CEN_tr_pctHSGrad

[,1]      [,2]       [,3]      [,4]      [,5]      [,6]       [,7]     
[1,] 0.0000000 0.05626431 0.0000000 0.1083716 0.0000000 0.01745962 0.1217066
[2,] 0.1779584 0.23398405 0.2031250 0.2886164 0.1550285 0.18727915 0.1535604
[3,] 0.2636364 0.29522529 0.2797643 0.3496641 0.2413361 0.24248088 0.1639839
[4,] 0.3461876 0.35250273 0.3594062 0.4088398 0.3135889 0.30051282 0.1748182
[5,] 0.5970102 0.53024575 0.5933278 0.5888122 0.5511145 0.47030594 0.2066523

In [75]:
df_HealthScore_C5

[,1] [,2]  [,3]  [,4]  [,5]  [,6]  [,7] 
[1,] 0.5  1.125 1.125 1.125 1.125 1.125 1.125
[2,] 0.5  1.125 1.125 1.125 1.125 1.125 1.125
[3,] 0.5  1.125 1.125 1.125 1.125 1.125 1.125
[4,] 0.5  1.375 1.375 1.375 1.375 1.375 1.375
[5,] 0.5  1.625 1.625 1.625 1.625 1.625 1.625

In [76]:
save(df_HealthScore_C5, df_CEN_tr_pctHSGrad, df_CEN_bg_pctHHincomeLT15K, df_EstMarketValue_C1, df_score_c4, file = "ewkm_k7_l3.RData")