In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import metrics
from sklearn.metrics import pairwise_distances
from sklearn import datasets
from sklearn.decomposition import PCA
from sklearn import cluster
from sklearn import preprocessing

1. Perform k-means on each of the features individually for some k. 
2. For each cluster measure some clustering performance metric like the Dunn's index or silhouette. 
3. Take the feature which gives you the best performance and add it to Sf
4. Perform k-means on Sf and each of the remaining features individually
5. Take the feature which gives you the best performance and add it to Sf
4. If you have reached the desired number of features stop, else go back to 4

In [4]:
dataset = datasets.load_iris()
X = dataset.data
y = dataset.target

In [41]:
n, m = X.shape[0], X.shape[1]
print(n, m)

150 4


In [21]:
X

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [80]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [83]:
pd.value_counts(pd.Series(y))

2    50
1    50
0    50
dtype: int64

* Perform k-means on each of the features individually for some k. 
* For each cluster measure some clustering performance metric like the Dunn's index or silhouette. 
* Take the feature which gives you the best performance and add it to Sf

In [92]:
for d in range(1,5):
    exec(f'X{d} = np.zeros(n)')
    for i in range(n):
        exec(f'X{d}[i] = X[i][d-1]')

In [93]:
score = [0]*m
for i in range(1, m+1):
    print("Now processing model %d" %i, ", which uses feature # %d only" %i)
    exec(f'model_{i} = cluster.KMeans(n_clusters=3)')
    exec(f'X{i} = X{i}[:, np.newaxis]')
    exec(f'model_{i}.fit(X{i})')
    exec(f'pred_y = model_{i}.labels_')
    print("Now let's compare the true class label to the class labels obtained by clustering")
    print(pd.value_counts(pd.Series(pred_y)))
    exec(f'score[i-1] = model_{i}.inertia_')
    print("For model %d:" %i,"the sum of squared distances of samples to their closest cluster center is %s" %score[i-1])

Now processing model 1 , which uses feature # 1 only
Now let's compare the true class label to the class labels obtained by clustering
2    63
1    52
0    35
dtype: int64
For model 1: the sum of squared distances of samples to their closest cluster center is 15.7581196581
Now processing model 2 , which uses feature # 2 only
Now let's compare the true class label to the class labels obtained by clustering
1    81
0    36
2    33
dtype: int64
For model 2: the sum of squared distances of samples to their closest cluster center is 5.26434343434
Now processing model 3 , which uses feature # 3 only
Now let's compare the true class label to the class labels obtained by clustering
0    58
1    50
2    42
dtype: int64
For model 3: the sum of squared distances of samples to their closest cluster center is 24.6580407225
Now processing model 4 , which uses feature # 4 only
Now let's compare the true class label to the class labels obtained by clustering
2    52
0    50
1    48
dtype: int64
For mo

In [108]:
selected_feature = score.index(min(score)) + 1
print("The # %d feature" % (score.index(min(score)) + 1), "gives the best performance")

The # 4 feature gives the best performance


* Perform k-means on Sf and each of the remaining features individually
* Take the feature which gives you the best performance and add it to Sf

In [109]:
selected_feature 

4

In [ ]:
score1 = [0]*m
for i in range(1, m+1):
    if i!= selected_feature:
        second_iter_X{i} = np.concatenate((X1{i}, X{selected_feature}), axis=1)
X        
#     print("Now processing model %d" %i, ", which uses feature # %d only" %i)
#     exec(f'model_{i} = cluster.KMeans(n_clusters=3)')
#     exec(f'X{i} = X{i}[:, np.newaxis]')
#     exec(f'model_{i}.fit(X{i})')
#     exec(f'pred_y = model_{i}.labels_')
#     print("Now let's compare the true class label to the class labels obtained by clustering")
#     print(pd.value_counts(pd.Series(pred_y)))
#     exec(f'score[i-1] = model_{i}.inertia_')
#     print("For model %d:" %i,"the sum of squared distances of samples to their closest cluster center is %s" %score[i-1])

In [106]:
np.concatenate((X1, X2), axis=1)

array([[ 5.1,  3.5],
       [ 4.9,  3. ],
       [ 4.7,  3.2],
       [ 4.6,  3.1],
       [ 5. ,  3.6],
       [ 5.4,  3.9],
       [ 4.6,  3.4],
       [ 5. ,  3.4],
       [ 4.4,  2.9],
       [ 4.9,  3.1],
       [ 5.4,  3.7],
       [ 4.8,  3.4],
       [ 4.8,  3. ],
       [ 4.3,  3. ],
       [ 5.8,  4. ],
       [ 5.7,  4.4],
       [ 5.4,  3.9],
       [ 5.1,  3.5],
       [ 5.7,  3.8],
       [ 5.1,  3.8],
       [ 5.4,  3.4],
       [ 5.1,  3.7],
       [ 4.6,  3.6],
       [ 5.1,  3.3],
       [ 4.8,  3.4],
       [ 5. ,  3. ],
       [ 5. ,  3.4],
       [ 5.2,  3.5],
       [ 5.2,  3.4],
       [ 4.7,  3.2],
       [ 4.8,  3.1],
       [ 5.4,  3.4],
       [ 5.2,  4.1],
       [ 5.5,  4.2],
       [ 4.9,  3.1],
       [ 5. ,  3.2],
       [ 5.5,  3.5],
       [ 4.9,  3.1],
       [ 4.4,  3. ],
       [ 5.1,  3.4],
       [ 5. ,  3.5],
       [ 4.5,  2.3],
       [ 4.4,  3.2],
       [ 5. ,  3.5],
       [ 5.1,  3.8],
       [ 4.8,  3. ],
       [ 5.1,  3.8],
       [ 4.6,