In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import metrics
from sklearn.metrics import pairwise_distances
from sklearn import datasets
from sklearn.decomposition import PCA
from sklearn import cluster
from sklearn import preprocessing

## Overall principal of iterated feature selection
1. Perform k-means on each of the features individually for some k. 
2. For each cluster measure some clustering performance metric like the Dunn's index or silhouette. 
3. Take the feature which gives you the best performance and add it to Sf
4. Perform k-means on Sf and each of the remaining features individually
5. Take the feature which gives you the best performance and add it to Sf
4. If you have reached the desired number of features stop, else go back to 4

In [4]:
dataset = datasets.load_iris()
X = dataset.data
y = dataset.target

In [41]:
n, m = X.shape[0], X.shape[1]
print(n, m)

150 4


In [21]:
X

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [80]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [83]:
pd.value_counts(pd.Series(y))

2    50
1    50
0    50
dtype: int64

### Feature selection - code version 1

* Perform k-means on each of the features individually for some k. 
* For each cluster measure some clustering performance metric like the Dunn's index or silhouette. 
* Take the feature which gives you the best performance and add it to Sf

In [165]:
for d in range(1,5):
    exec(f'X{d} = np.zeros(n)')
    for i in range(n):
        exec(f'X{d}[i] = X[i][d-1]')

In [93]:
score = [0]*m
for i in range(1, m+1):
    print("Now processing model %d" %i, ", which uses feature # %d only" %i)
    exec(f'model_{i} = cluster.KMeans(n_clusters=3)')
    exec(f'X{i} = X{i}[:, np.newaxis]')
    exec(f'model_{i}.fit(X{i})')
    exec(f'pred_y = model_{i}.labels_')
    print("Now let's compare the true class label to the class labels obtained by clustering")
    print(pd.value_counts(pd.Series(pred_y)))
    exec(f'score[i-1] = model_{i}.inertia_')
    print("For model %d:" %i,"the sum of squared distances of samples to their closest cluster center is %s" %score[i-1])

Now processing model 1 , which uses feature # 1 only
Now let's compare the true class label to the class labels obtained by clustering
2    63
1    52
0    35
dtype: int64
For model 1: the sum of squared distances of samples to their closest cluster center is 15.7581196581
Now processing model 2 , which uses feature # 2 only
Now let's compare the true class label to the class labels obtained by clustering
1    81
0    36
2    33
dtype: int64
For model 2: the sum of squared distances of samples to their closest cluster center is 5.26434343434
Now processing model 3 , which uses feature # 3 only
Now let's compare the true class label to the class labels obtained by clustering
0    58
1    50
2    42
dtype: int64
For model 3: the sum of squared distances of samples to their closest cluster center is 24.6580407225
Now processing model 4 , which uses feature # 4 only
Now let's compare the true class label to the class labels obtained by clustering
2    52
0    50
1    48
dtype: int64
For mo

In [167]:
selected_feature = score.index(min(score)) + 1
print("The # %d feature" % (score.index(min(score)) + 1), "gives the best performance")

The # 4 feature gives the best performance


* Perform k-means on Sf and each of the remaining features individually
* Take the feature which gives you the best performance and add it to Sf

In [109]:
selected_feature 

4

In [ ]:
score1 = [0]*m
for i in range(1, m+1):
    if i!= selected_feature:
        second_iter_X{i} = np.concatenate((X1{i}, X{selected_feature}), axis=1)
X        
#     print("Now processing model %d" %i, ", which uses feature # %d only" %i)
#     exec(f'model_{i} = cluster.KMeans(n_clusters=3)')
#     exec(f'X{i} = X{i}[:, np.newaxis]')
#     exec(f'model_{i}.fit(X{i})')
#     exec(f'pred_y = model_{i}.labels_')
#     print("Now let's compare the true class label to the class labels obtained by clustering")
#     print(pd.value_counts(pd.Series(pred_y)))
#     exec(f'score[i-1] = model_{i}.inertia_')
#     print("For model %d:" %i,"the sum of squared distances of samples to their closest cluster center is %s" %score[i-1])

In [106]:
np.concatenate((X1, X2), axis=1)

array([[ 5.1,  3.5],
       [ 4.9,  3. ],
       [ 4.7,  3.2],
       [ 4.6,  3.1],
       [ 5. ,  3.6],
       [ 5.4,  3.9],
       [ 4.6,  3.4],
       [ 5. ,  3.4],
       [ 4.4,  2.9],
       [ 4.9,  3.1],
       [ 5.4,  3.7],
       [ 4.8,  3.4],
       [ 4.8,  3. ],
       [ 4.3,  3. ],
       [ 5.8,  4. ],
       [ 5.7,  4.4],
       [ 5.4,  3.9],
       [ 5.1,  3.5],
       [ 5.7,  3.8],
       [ 5.1,  3.8],
       [ 5.4,  3.4],
       [ 5.1,  3.7],
       [ 4.6,  3.6],
       [ 5.1,  3.3],
       [ 4.8,  3.4],
       [ 5. ,  3. ],
       [ 5. ,  3.4],
       [ 5.2,  3.5],
       [ 5.2,  3.4],
       [ 4.7,  3.2],
       [ 4.8,  3.1],
       [ 5.4,  3.4],
       [ 5.2,  4.1],
       [ 5.5,  4.2],
       [ 4.9,  3.1],
       [ 5. ,  3.2],
       [ 5.5,  3.5],
       [ 4.9,  3.1],
       [ 4.4,  3. ],
       [ 5.1,  3.4],
       [ 5. ,  3.5],
       [ 4.5,  2.3],
       [ 4.4,  3.2],
       [ 5. ,  3.5],
       [ 5.1,  3.8],
       [ 4.8,  3. ],
       [ 5.1,  3.8],
       [ 4.6,

### Feature selection - code version 2
#### Try to organize data into functions

In [116]:
def feature_selection(m, n, X, num_clusters, desired_num_of_feature):
    for i in range(desired_num_of_feature):
        # The first iteration, perform k-means on each of the features individually and 
        # take the feature which gives you the best performance   
        if i == 0:
            #generate data points X_iter_1 with only one feature
            for d in range(1, n+1):
                exec(f 'X_iter{i+1}_{d} = np.zeros(n)') 
                #reference: https://stackoverflow.com/questions/6181935/how-do-you-create-different-variable-names-while-in-a-loop
                #https://docs.python.org/3/whatsnew/3.6.html
                
                for j in range(n):
                    exec(f'X_iter{i+1}_{d}[j] = X[j][d-1]')
            
            #Now perform k-means on each of the featurees individually 
            for j in range(1, m+1):
                print("Now processing model %d" %j, ", which uses feature # %d only" %j)
                exec(f'model_{j} = cluster.KMeans(n_clusters=num_clusters)')
                # Need to add a dimension to the generate data points in order to fit model
                exec(f'X_iter{i+1}_{j} = X{j}[:, np.newaxis]')
                # Now fit the data points with only one feature
                exec(f'model_{i}.fit(X{i})')
                exec(f'pred_y = model_{i}.labels_')
                print("Now let's compare the true class label to the class labels obtained by clustering")
                print(pd.value_counts(pd.Series(pred_y)))
                exec(f'score[i-1] = model_{i}.inertia_')
                print("For model %d:" %i,"the sum of squared distances of samples to their closest cluster center is %s" %score[i-1])


### Feature selection - code version 3
#### Organize Iris dataset into a dataframe in order to better imitate our project data format

In [3]:
dataset = datasets.load_iris()
X = dataset.data
y = dataset.target

In [52]:
dir(dataset)

['DESCR', 'data', 'feature_names', 'target', 'target_names']

In [4]:
iris = pd.DataFrame(X)
iris.columns = dataset.feature_names

In [54]:
iris

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
5                  5.4               3.9                1.7               0.4
6                  4.6               3.4                1.4               0.3
7                  5.0               3.4                1.5               0.2
8                  4.4               2.9                1.4               0.2
9                  4.9               3.1                1.5               0.1
10                 5.4               3.7                1.5               0.2
11                 4.8               3.4                1.6               0.2
12                 4.8               3.0                1.4               0.1
13                 4.3               3.0                1.1               0.1
14                 5.8               4.0                1.2               0.2
15                 5.7               4.4                1.5               0.4
16                 5.4               3.9                1.3               0.4
17                 5.1               3.5                1.4               0.3
18                 5.7               3.8                1.7               0.3
19                 5.1               3.8                1.5               0.3
20                 5.4               3.4                1.7               0.2
21                 5.1               3.7                1.5               0.4
22                 4.6               3.6                1.0               0.2
23                 5.1               3.3                1.7               0.5
24                 4.8               3.4                1.9               0.2
25                 5.0               3.0                1.6               0.2
26                 5.0               3.4                1.6               0.4
27                 5.2               3.5                1.5               0.2
28                 5.2               3.4                1.4               0.2
29                 4.7               3.2                1.6               0.2
..                 ...               ...                ...               ...
120                6.9               3.2                5.7               2.3
121                5.6               2.8                4.9               2.0
122                7.7               2.8                6.7               2.0
123                6.3               2.7                4.9               1.8
124                6.7               3.3                5.7               2.1
125                7.2               3.2                6.0               1.8
126                6.2               2.8                4.8               1.8
127                6.1               3.0                4.9               1.8
128                6.4               2.8                5.6               2.1
129                7.2               3.0                5.8               1.6
130                7.4               2.8                6.1               1.9
131                7.9               3.8                6.4               2.0
132                6.4               2.8                5.6               2.2
133                6.3               2.8                5.1               1.5
134                6.1               2.6                5.6               1.4
135                7.7               3.0                6.1               2.3
136                6.3               3.4                5.6               2.4
137                6.4               3.1                5.5               1.8
138                6.0               3.0                4.8               1.8
139                6.9     

In [5]:
n, m = iris.shape[0], iris.shape[1]
print("number of data points:", n, ". number of variables:", m)

number of data points: 150 . number of variables: 4


In [6]:
model_test = cluster.KMeans(n_clusters=3)
model_test.fit(iris) 
pred_y=model_test.labels_
print("True class labels", "\n", pd.value_counts(pd.Series(y)))
print("Clustered class labels:", "\n", pd.value_counts(pd.Series(pred_y)))

True class labels 
 2    50
1    50
0    50
dtype: int64
Clustered class labels: 
 0    62
1    50
2    38
dtype: int64


In [20]:
score = np.zeros([num_of_iter, m])
# score = pd.DataFrame(score)
# score.loc[:,0:2]
score[:, [0, 2]]

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [21]:
exclude_columns = [3]
include_columns = [i for i in range(np.shape(score)[1]) if i not in exclude_columns]
extractedData = score[:,include_columns]

In [37]:
iris.columns[exclude_columns]

Index(['petal width (cm)', 'sepal width (cm)', 'sepal width (cm)'], dtype='object')

In [36]:
exclude_columns 

[3, 1, 1]

In [29]:
include_columns

[0, 2]

In [30]:
iris.loc[:, exclude_columns]

KeyError: 'None of [[3, 1, 0]] are in the [columns]'

In [34]:
# let's assume there are 3 clusters
num_of_cluster = 3
num_of_iter = 3
model = cluster.KMeans(n_clusters=num_of_cluster)
score = np.zeros([num_of_iter, m])
exclude_columns = []
include_columns = [i for i in range(np.shape(score)[1]) if i not in exclude_columns]
# Let's assume we're going to select 3 features out of 4 features, therefore we're going to iterate 3 times
for iteration in range(3):
    # The first iteration, we're going to test clustering models on each individual variables
    if iteration == 0:
        print("Now processing iteration %d" %iteration, "\n")   
        for i in range(m):
            model.fit(iris[[i]])
            pred_y = model.labels_
            print("cluster labels based on variable %s:" %iris.columns[i], "\n", pd.value_counts(pd.Series(pred_y)))
            score[iteration][i] = model.inertia_
            print("the sum of squared distances of samples to their closest cluster center based on variable %s" \
                  %iris.columns[i], "is:", score[iteration][i])   
        score = score[:,include_columns]
        selected_feature_index = np.argmin(score[iteration], axis=0) 
        selected_feature_score = np.amin(score[iteration], axis=0) 
        selected_feature = iris[[selected_feature_index]]
        exclude_columns.append(selected_feature_index)
        print("Conclusion: cluster based on variable %s" %iris.columns[selected_feature_index], "gives the best performance", "\n") 
    #for following iteration, we're going to add the rest the feature to the selected feature and perform cluster model
    else:
        print("Now processing iteration %d" %iteration, "\n") 
        for i in range(m):
            if i not in exclude_columns:
                
                data = pd.concat([selected_feature, iris[[i]]], axis=1)
                model.fit(data)
                pred_y = model.labels_
                print("cluster labels based on variables:", data.columns, "\n", pd.value_counts(pd.Series(pred_y)))
                score[iteration][i] = model.inertia_
                print("the sum of squared distances of samples to their closest cluster center based on variables:", \
                 data.columns, "is:", score[iteration][i]) 
        include_columns = [i for i in range(np.shape(score)[1]) if i not in exclude_columns]
        score = score[:,include_columns]
        selected_feature_index = np.argmin(score[iteration], axis=0) 
        selected_feature_score = np.amin(score[iteration], axis=0) 
        selected_feature = pd.concat([selected_feature, iris[[selected_feature_index]]], axis=1)
        exclude_columns.append(selected_feature_index)
        print("Conclusion: cluster based on variable %s" %iris.columns[exclude_columns], "gives the best performance", "\n") 
print("Selected features are %s" %iris.columns[exclude_columns])

Now processing iteration 0 

cluster labels based on variable sepal length (cm): 
 2    63
0    52
1    35
dtype: int64
the sum of squared distances of samples to their closest cluster center based on variable sepal length (cm) is: 15.7581196581
cluster labels based on variable sepal width (cm): 
 0    81
1    36
2    33
dtype: int64
the sum of squared distances of samples to their closest cluster center based on variable sepal width (cm) is: 5.26434343434
cluster labels based on variable petal length (cm): 
 2    54
0    50
1    46
dtype: int64
the sum of squared distances of samples to their closest cluster center based on variable petal length (cm) is: 24.5138312399
cluster labels based on variable petal width (cm): 
 0    52
1    50
2    48
dtype: int64
the sum of squared distances of samples to their closest cluster center based on variable petal width (cm) is: 4.93217435897
Conclusion: cluster based on variable petal width (cm) gives the best performance 

Now processing iteratio